services:
  mysql:
    image: mysql:8.0

    container_name: enterprise_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: enterprise_ecommerce_db

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: